version = 1
name = "hugo-blog"
license = "MIT"
licenselink = "https://github.com/akitectio/hugo-blog/blob/main/LICENSE"
description = "Blog Hugo Theme"
homepage = "https://github.com/akitectio/hugo-blog"
demosite = "https://hugo-blog.github.io"
tags = ["blog", "clean", "responsive", "dark", "theme"]

features = [
  "cover-image",
  "favicon",
  "multilingual",
  "pagination",
  "social-menu",
  "syntax-highlighting",
  "SEO Optimized",
]

[author]
name = "Trần Đức Duy"
homepage = "https://github.com/akitectio"

[original]
name = "Trần Đức Duy"
homepage = "https://github.com/akitectio"
repo = "https://github.com/akitectio"

[module]
[module.hugoVersion]
extended = true
min = "0.83.0"
